Product.create(id: 1, product_name: '銀イオン詰替え用（6ppm）2L×10セット', price: 33500, description: "3種類の保湿剤を配合し、手に潤いを与えるだけでなく、さらさら・すべすべ感も与えます。有効成分として「ベンザルコニウム塩化物」使用。広範囲の微生物に対して短時間で効力を発揮します。手でつぶせる容器です。", stock: 0, model_number: "AG010", product_type: "消毒液", point: 3.69, sales_profit: 14000, display: true, product_link: "https://www.musubimusubi.com/products/introduction_silver_ion_water")
product = Product.find(1)
product.images.attach([io: File.open('app/assets/images/6ppm×2L_1.webp'), filename: '6ppm×2L_1.webp'])
product.images.attach([io: File.open('app/assets/images/6ppm×2L_2.webp'), filename: '6ppm×2L_2.webp'])
product.images.attach([io: File.open('app/assets/images/6ppm×2L_3.webp'), filename: '6ppm×2L_3.webp'])

Product.create(id: 2, product_name: '銀イオン詰替え用（20ppm）2L×10セット', price: 38500, description: "1．ポンプはゆっくり押して、適量（500円玉程度）をお取りください。 2． およそ15秒間、両手にまんべんなく塗り広げてください。 3．アルコールが完全に揮発するまで両手をすり合わせてください。", stock: 1, model_number: "AG011", product_type: "消毒液", point: 4.24, sales_profit: 11000, display: true, product_link: "https://www.musubimusubi.com/products/introduction_silver_ion_water")
product = Product.find(2)
product.images.attach([io: File.open('app/assets/images/20ppm×2L_1.webp'), filename: '20ppm×2L_1.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×2L_2.webp'), filename: '20ppm×2L_2.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×2L_3.webp'), filename: '20ppm×2L_3.webp'])

Product.create(id: 3, product_name: '銀イオン詰替え用（6ppm）20L', price: 28000, description: "エンベロープのあるウイルスはアルコール消毒剤が効きやすく、ノンエンベロープウイルスは一般的なアルコール消毒剤が効きにくい傾向。そのためアルコール手指消毒剤はノンエンベロープウイルスを含む広範囲のウイルスを除去できるものが有効的。", stock: 2, model_number: "AG012", product_type: "消毒液", point: 3.08, sales_profit: 14000, display: true, product_link: "https://www.musubimusubi.com/products/introduction_silver_ion_water")
product = Product.find(3)
product.images.attach([io: File.open('app/assets/images/6ppm×20L_1.webp'), filename: '6ppm×20L_1.webp'])
product.images.attach([io: File.open('app/assets/images/6ppm×20L_2.webp'), filename: '6ppm×20L_2.webp'])
product.images.attach([io: File.open('app/assets/images/6ppm×20L_3.webp'), filename: '6ppm×20L_3.webp'])

Product.create(id: 4, product_name: '銀イオン詰替え用（20ppm）20L', price: 33000, description: "食塩より100倍以上も安全という経口性を持ち、赤ちゃんやペットのいる環境でも安心。（経口急性毒性推定値（ATE）検査済み） 無香料なのでマスクの除菌にも気軽に使えます。ウィルスや細菌を99.9%以上除菌。（専門機関による抗ウィルス性検査済み）", stock: 3, model_number: "AG013", product_type: "消毒液", point: 3.63, sales_profit: 11000, display: true, product_link: "https://www.musubimusubi.com/products/introduction_silver_ion_water")
product = Product.find(4)
product.images.attach([io: File.open('app/assets/images/20ppm×20L_1.webp'), filename: '20ppm×20L_1.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×20L_2.webp'), filename: '20ppm×20L_2.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×20L_3.webp'), filename: '20ppm×20L_3.webp'])

Product.create(id: 5, product_name: '銀イオンスプレー（20ppm）200mL', price: 1000, description: "食塩より100倍以上も安全という経口性を持ち、赤ちゃんやペットのいる環境でも安心。（経口急性毒性推定値（ATE）検査済み） 無香料なのでマスクの除菌にも気軽に使えます。ウィルスや細菌を99.9%以上除菌。（専門機関による抗ウィルス性検査済み）", stock: 3, model_number: "AG014", product_type: "消毒液", point: 0.11, sales_profit: 1000, display: true, product_link: "https://www.musubimusubi.com/products/introduction_silver_ion_water")
product = Product.find(5)
product.images.attach([io: File.open('app/assets/images/20ppm×200mL_1.webp'), filename: '20ppm×200mL_1.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×200mL_2.webp'), filename: '20ppm×200mL_2.webp'])
product.images.attach([io: File.open('app/assets/images/20ppm×200mL_3.webp'), filename: '20ppm×200mL_3.webp'])

Product.create(id: 6, product_name: 'EPA+DHA+ビタミンD3 リキッド 150mL', price: 7400, description: "主成分含有量（5mlあたり）\n・オメガ３脂肪酸：3,000mg\n・EPA：1,500mg\n・DHA：1,500mg\n・ビタミンD３：10.0mcg\n\n1日5mlでEPA:1,500mg、DHA:1,500mgと、高容量のオメガ3脂肪酸と、ビタミンD₃を摂取できます。\n\n体内でつくることができないオメガ3脂肪酸は、必須脂肪酸と呼ばれており、食事やサプリメントから摂取する必要があります。\nまた、脂肪酸と相性のよい脂溶性のビタミンD₃を同時に摂取することで、さらなる健康維持をサポートします。\n\nリキッドタイプなので、摂取量の調節がしやすく、錠剤やカプセルが苦手な方でも手軽に摂取できます。\nまた、レモンの風味をつけているため、そのままではもちろん、お食事やお飲み物に混ぜてもお召し上がりいただけます。", stock: 0, model_number: "ND001", product_type: "サプリメント", point: 0.81, sales_profit: 2960, display: true, product_link: "https://www.musubimusubi.com/products/introduction_dha_epa_supplement")
product = Product.find(6)
product.images.attach([io: File.open('app/assets/images/DHA_EPA.webp'), filename: 'DHA_EPA.webp'])

Product.create(id: 7, product_name: 'EPA+DHA+ビタミンD3 リキッド キッズ 100mL', price: 5500, description: "魚が苦手なお子様や日光を浴びる機会の少ないお子様の栄養補給にお勧めの商品です。\n\n主成分含有量（5mlあたり）\n・オメガ３脂肪酸：600mg\n・EPA：300mg\n・DHA：300mg\n・ビタミンD３：2.0mcg\n\n体内でつくることができないオメガ3脂肪酸は、必須脂肪酸と呼ばれており、食事やサプリメントから摂取する必要があります。\nまた、ビタミンD₃もプラスすることで、発育段階のお子様の健康をサポートします。\n\nリキッドタイプなのでお子様の年齢に合わせて摂取量を簡単に調節できます。\nオレンジとベリーの風味で、そのままでも、お食事やお飲み物に混ぜても、おいしくお召し上がりいただけます。\n\n< 目安量 >\n6歳以下：1日1mL\n7歳以上：1日2.5mL", stock: 0, model_number: "ND002", product_type: "サプリメント", point: 0.61, sales_profit: 2200, display: true, product_link: "https://www.musubimusubi.com/products/introduction_dha_epa_supplement")
product = Product.find(7)
product.images.attach([io: File.open('app/assets/images/DHA_EPA.webp'), filename: 'DHA_EPA.webp'])

Product.create(id: 8, product_name: 'ItoiXソックス', price: 1950, description: "呼吸する、和紙の靴下。\n\n◆圧倒的なドライ感\n◆他社製品比較で15倍のの吸水性を実現。\n主原料である「マニラ麻」は、表面に無数の穴が空いているのが特長。\n汗や雨などの水分が、地面を踏みしめるタイミングで吸収する空気によりすぐに押し出され、肌との間に水分が留まることがない仕組み。\nムレによる不快感を大幅に軽減します。\n\n◆消臭書の力96〜99%\n靴下の主原料である「マニラ麻」は、汗の吸水・速乾の特性でムレの留まりを抑制します。\nさらに、臭いの元とされるイソ吉草酸ガス発生時に、ガスの滞留時間を短縮します。\n\n◆薄くて強靭。商品化基準の3倍の強度\n\n◆超軽量で抜群のフィット感\n驚きの25g", stock: 19, model_number:"IX001", product_type: "スポーツ", point: 0.21, sales_profit: 750, display: true, product_link: "https://www.musubimusubi.com/products/introduction_itoix")
product = Product.find(8)
product.images.attach([io: File.open('app/assets/images/itoix_1.webp'), filename: 'itoix_1.webp'])
product.images.attach([io: File.open('app/assets/images/itoix_2.webp'), filename: 'itoix_2.webp'])
product.images.attach([io: File.open('app/assets/images/itoix_3.webp'), filename: 'itoix_3.webp'])
product.images.attach([io: File.open('app/assets/images/itoix_4.webp'), filename: 'itoix_4.webp'])
product.images.attach([io: File.open('app/assets/images/itoix_5.webp'), filename: 'itoix_5.webp'])